# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/sturgeon/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/sturgeon/proprietary/app/AnalogComplicationWatchFace/AnalogComplicationWatchFace.apk:system/app/AnalogComplicationWatchFace/AnalogComplicationWatchFace.apk \
    vendor/huawei/sturgeon/proprietary/app/ClockworkFlashlight/ClockworkFlashlight.apk:system/app/ClockworkFlashlight/ClockworkFlashlight.apk \
    vendor/huawei/sturgeon/proprietary/app/ClockworkFrameworkPackageStubs/ClockworkFrameworkPackageStubs.apk:system/app/ClockworkFrameworkPackageStubs/ClockworkFrameworkPackageStubs.apk \
    vendor/huawei/sturgeon/proprietary/app/ClockworkPhotosWatchFace/ClockworkPhotosWatchFace.apk:system/app/ClockworkPhotosWatchFace/ClockworkPhotosWatchFace.apk \
    vendor/huawei/sturgeon/proprietary/app/ClockworkSearch/ClockworkSearch.apk:system/app/ClockworkSearch/ClockworkSearch.apk \
    vendor/huawei/sturgeon/proprietary/app/CtsShimPrebuilt/CtsShimPrebuilt.apk:system/app/CtsShimPrebuilt/CtsShimPrebuilt.apk \
    vendor/huawei/sturgeon/proprietary/app/DigitalComplicationWatchFace/DigitalComplicationWatchFace.apk:system/app/DigitalComplicationWatchFace/DigitalComplicationWatchFace.apk \
    vendor/huawei/sturgeon/proprietary/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk:system/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk \
    vendor/huawei/sturgeon/proprietary/app/GoogleExtShared/GoogleExtShared.apk:system/app/GoogleExtShared/GoogleExtShared.apk \
    vendor/huawei/sturgeon/proprietary/app/GoogleTTSPrebuiltWearable/GoogleTTSPrebuiltWearable.apk:system/app/GoogleTTSPrebuiltWearable/GoogleTTSPrebuiltWearable.apk \
    vendor/huawei/sturgeon/proprietary/app/MusicStub/MusicStub.apk:system/app/MusicStub/MusicStub.apk \
    vendor/huawei/sturgeon/proprietary/app/PrebuiltDeskClockMicroApp/PrebuiltDeskClockMicroApp.apk:system/app/PrebuiltDeskClockMicroApp/PrebuiltDeskClockMicroApp.apk \
    vendor/huawei/sturgeon/proprietary/app/RemindersPrebuiltWearable/RemindersPrebuiltWearable.apk:system/app/RemindersPrebuiltWearable/RemindersPrebuiltWearable.apk \
    vendor/huawei/sturgeon/proprietary/app/TalkbackWearPrebuilt/TalkbackWearPrebuilt.apk:system/app/TalkbackWearPrebuilt/TalkbackWearPrebuilt.apk \
    vendor/huawei/sturgeon/proprietary/app/TranslatePrebuiltWearable/TranslatePrebuiltWearable.apk:system/app/TranslatePrebuiltWearable/TranslatePrebuiltWearable.apk \
    vendor/huawei/sturgeon/proprietary/app/WearHandwriting/WearHandwriting.apk:system/app/WearHandwriting/WearHandwriting.apk \
    vendor/huawei/sturgeon/proprietary/app/WearKeyboard/WearKeyboard.apk:system/app/WearKeyboard/WearKeyboard.apk \
    vendor/huawei/sturgeon/proprietary/bin/bt_addr_format.sh:system/bin/bt_addr_format.sh \
    vendor/huawei/sturgeon/proprietary/bin/ClockworkProxy:system/bin/ClockworkProxy \
    vendor/huawei/sturgeon/proprietary/bin/delta_panel.sh:system/bin/delta_panel.sh \
    vendor/huawei/sturgeon/proprietary/bin/shd:system/bin/shd \
    vendor/huawei/sturgeon/proprietary/etc/regulatory_info.png:system/etc/regulatory_info.png \
    vendor/huawei/sturgeon/proprietary/etc/Tfa98xx.cnt:system/etc/Tfa98xx.cnt \
    vendor/huawei/sturgeon/proprietary/framework/clockwork-system.jar:system/framework/clockwork-system.jar \
    vendor/huawei/sturgeon/proprietary/framework/com.google.android.wearable.jar:system/framework/com.google.android.wearable.jar \
    vendor/huawei/sturgeon/proprietary/framework/wear-service.jar:system/framework/wear-service.jar \
    vendor/huawei/sturgeon/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/huawei/sturgeon/proprietary/lib/hw/audio.primary.sturgeon.so:system/lib/hw/audio.primary.sturgeon.so \
    vendor/huawei/sturgeon/proprietary/lib/hw/lights.sturgeon.so:system/lib/hw/lights.sturgeon.so \
    vendor/huawei/sturgeon/proprietary/lib/hw/power.sturgeon.so:system/lib/hw/power.sturgeon.so \
    vendor/huawei/sturgeon/proprietary/lib/hw/sensors.sturgeon.so:system/lib/hw/sensors.sturgeon.so \
    vendor/huawei/sturgeon/proprietary/lib/libclockwork-bluetooth-jni.so:system/lib/libclockwork-bluetooth-jni.so \
    vendor/huawei/sturgeon/proprietary/lib/libclockwork_proxy_jni.so:system/lib/libclockwork_proxy_jni.so \
    vendor/huawei/sturgeon/proprietary/lib/libexTfa98xx.so:system/lib/libexTfa98xx.so \
    vendor/huawei/sturgeon/proprietary/lib/libhwui.so:system/lib/libhwui.so \
    vendor/huawei/sturgeon/proprietary/lib/libwear-bluetooth-jni.so:system/lib/libwear-bluetooth-jni.so \
    vendor/huawei/sturgeon/proprietary/priv-app/ChargeDetection/ChargeDetection.apk:system/priv-app/ChargeDetection/ChargeDetection.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/ClockworkAmbient/ClockworkAmbient.apk:system/priv-app/ClockworkAmbient/ClockworkAmbient.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/ClockworkBluetooth/ClockworkBluetooth.apk:system/priv-app/ClockworkBluetooth/ClockworkBluetooth.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/ClockworkBugReportSender/ClockworkBugReportSender.apk:system/priv-app/ClockworkBugReportSender/ClockworkBugReportSender.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/ClockworkHomeGoogle/ClockworkHomeGoogle.apk:system/priv-app/ClockworkHomeGoogle/ClockworkHomeGoogle.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/ClockworkPhone/ClockworkPhone.apk:system/priv-app/ClockworkPhone/ClockworkPhone.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/ClockworkSettings/ClockworkSettings.apk:system/priv-app/ClockworkSettings/ClockworkSettings.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/ClockworkSetupWizard/ClockworkSetupWizard.apk:system/priv-app/ClockworkSetupWizard/ClockworkSetupWizard.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/CtsShimPrivPrebuilt/CtsShimPrivPrebuilt.apk:system/priv-app/CtsShimPrivPrebuilt/CtsShimPrivPrebuilt.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/DailyTracking/DailyTracking.apk:system/priv-app/DailyTracking/DailyTracking.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/GoogleExtServices/GoogleExtServices.apk:system/priv-app/GoogleExtServices/GoogleExtServices.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/GooglePackageInstaller/GooglePackageInstaller.apk:system/priv-app/GooglePackageInstaller/GooglePackageInstaller.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk:system/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/HeartRate/HeartRate.apk:system/priv-app/HeartRate/HeartRate.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/HuaweiMember/HuaweiMember.apk:system/priv-app/HuaweiMember/HuaweiMember.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/HwOemSetup/HwOemSetup.apk:system/priv-app/HwOemSetup/HwOemSetup.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/HwWatchface3D/HwWatchface3D.apk:system/priv-app/HwWatchface3D/HwWatchface3D.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/HwWatchface/HwWatchface.apk:system/priv-app/HwWatchface/HwWatchface.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/HwWearable/HwWearable.apk:system/priv-app/HwWearable/HwWearable.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/Maintenance/Maintenance.apk:system/priv-app/Maintenance/Maintenance.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/MinModWatchfaces/MinModWatchfaces.apk:system/priv-app/MinModWatchfaces/MinModWatchfaces.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/MobileSignalDetector/MobileSignalDetector.apk:system/priv-app/MobileSignalDetector/MobileSignalDetector.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/PrebuiltGmsCoreForClockwork_FitnessSidecar/PrebuiltGmsCoreForClockwork_FitnessSidecar.apk:system/priv-app/PrebuiltGmsCoreForClockwork_FitnessSidecar/PrebuiltGmsCoreForClockwork_FitnessSidecar.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/PrebuiltGmsCoreForClockworkWearable/PrebuiltGmsCoreForClockworkWearable.apk:system/priv-app/PrebuiltGmsCoreForClockworkWearable/PrebuiltGmsCoreForClockworkWearable.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/PrebuiltGmsCoreForClockwork_WearableSidecar/PrebuiltGmsCoreForClockwork_WearableSidecar.apk:system/priv-app/PrebuiltGmsCoreForClockwork_WearableSidecar/PrebuiltGmsCoreForClockwork_WearableSidecar.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/PrebuiltWearsky/PrebuiltWearsky.apk:system/priv-app/PrebuiltWearsky/PrebuiltWearsky.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/StatementService/StatementService.apk:system/priv-app/StatementService/StatementService.apk \
    vendor/huawei/sturgeon/proprietary/priv-app/WristGesturesTutorial/WristGesturesTutorial.apk:system/priv-app/WristGesturesTutorial/WristGesturesTutorial.apk \
    vendor/huawei/sturgeon/proprietary/usr/idc/AVRCP.idc:system/usr/idc/AVRCP.idc \
    vendor/huawei/sturgeon/proprietary/usr/idc/synaptics_dsx.idc:system/usr/idc/synaptics_dsx.idc \
    vendor/huawei/sturgeon/proprietary/usr/keychars/synaptics_dsx.kcm:system/usr/keychars/synaptics_dsx.kcm \
    vendor/huawei/sturgeon/proprietary/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
    vendor/huawei/sturgeon/proprietary/usr/keylayout/qpnp_pon.kl:system/usr/keylayout/qpnp_pon.kl \
    vendor/huawei/sturgeon/proprietary/usr/keylayout/synaptics_dsx.kl:system/usr/keylayout/synaptics_dsx.kl \
    vendor/huawei/sturgeon/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
    vendor/huawei/sturgeon/proprietary/vendor/firmware/4343A0.hcd:system/vendor/firmware/4343A0.hcd \
    vendor/huawei/sturgeon/proprietary/vendor/firmware/a330_pfp.fw:system/vendor/firmware/a330_pfp.fw \
    vendor/huawei/sturgeon/proprietary/vendor/firmware/a330_pm4.fw:system/vendor/firmware/a330_pm4.fw \
    vendor/huawei/sturgeon/proprietary/vendor/firmware/fw_bcmdhd.bin:system/vendor/firmware/fw_bcmdhd.bin \
    vendor/huawei/sturgeon/proprietary/vendor/firmware/Ofilm.img:system/vendor/firmware/Ofilm.img \
    vendor/huawei/sturgeon/proprietary/vendor/firmware/Truly.img:system/vendor/firmware/Truly.img \
    vendor/huawei/sturgeon/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/egl/libplayback_adreno.so:system/vendor/lib/egl/libplayback_adreno.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libacdb-mcs.so:system/vendor/lib/libacdb-mcs.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/huawei/sturgeon/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so
